# Generated by Django 4.0.4 on 2022-05-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField()),
                ('item_quantities', models.TextField()),
                ('coupons', models.TextField()),
                ('grand_total', models.TextField()),
            ],
        ),
    ]
